  
  type Company {
    id:Int
    name:String
    users:[User]
  }
  type User {
    id:Int
    firstName:String
    lastName:String
    fullName:String
    email:String
    company:Company
  }
  input CreateUserInput {
    firstName: String
    lastName: String
    email: String
  }
  type Mutation {
    createUser(createUserInput: CreateUserInput) : User
  }
  type Query {
    something: String
    user(id: Int) : User
    users : [User]
    companies: [Company]
  }
  schema {
    query: Query
    mutation: Mutation
  }