  type Customer {
    id:Int
    firstName:String
    lastName:String
    fullName:String
    email:String
    website:String
  }

  type Company {
    id:Int
    name:String
    users:[User]
  }
  type User {
    id:Int
    firstName:String
    lastName:String
    fullName:String
    email:String
    company:[Company]
    eao:String
  }

  input CreateCustomerInput {
    id:Int
    firstName:String
    lastName:String
    fullName:String
    email:String
    website:String
  }

  input CreateUserInput {
    id: Int
    firstName: String
    lastName: String
    email: String
  }
  input CreateCompanyInput {
    id: Int
    name: String
    userId: [Int]
  }
  type Mutation {
    createUser(createUserInput: CreateUserInput) : User
    createCustomer(createCustomerInput: CreateCustomerInput) : Customer
    createCompany(createCompanyInput: CreateCompanyInput) : Company
  }
  type Query {
    something: String
    user(id: Int) : User
    users: [User]
    companies: [Company]
    customers:[Customer]
    customer(id: Int) : Customer
  }
  schema {
    query: Query
    mutation: Mutation
  }